services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
  backup:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_ACCOUNT: "credentials.json"
    volumes:
      - ./data:/data
    environment:
      DIRECTORY: /data
      DRIVE_BACKUP_DIR: "1pBX-Lt3upeb519D17_XK4PH-Mbzbmbud"
      BACKUP_INTERVAL: 1d